# Generated by Django 2.2.28 on 2022-05-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='icon',
            field=models.URLField(blank=True, null=True, verbose_name='Map Icon'),
        ),
        migrations.AddField(
            model_name='address',
            name='international_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='International Phone Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='location_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='address',
            name='place_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Place Id'),
        ),
        migrations.AddField(
            model_name='address',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='icon',
            field=models.URLField(blank=True, null=True, verbose_name='Map Icon'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='international_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='International Phone Number'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='location_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='place_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Place Id'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='address',
            name='gmap_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='waze_url',
            field=models.URLField(blank=True, null=True, verbose_name='Waze Url'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='gmap_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='waze_url',
            field=models.URLField(blank=True, null=True, verbose_name='Waze Url'),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicallocality',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
